# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1871fe48f776a3bdd3115db454bae574b8164a7b14a1800f5c361cb09ea8f5ad90f4e165e1819b9f51f75bcd0fad292625f99c98e0daaeec131e6850e444cd6a

test:
  secret_key_base: 49200d863979fa584f06a24a03d84bda8a554473ced6dacde32620a683d361a2cd8d9863f56f3afaf2373fa4fc7c29ec14e486e71ab69a8a887c2dab4f5fc418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
